In [1]:
import numpy as np

In [4]:
persontype = np.dtype({'names':['name', 'age', 'chinese', 'math', 'english'],
                      'formats':['S32', 'i', 'f', 'f', 'f']})
peoples = np.array([("ZhangFei", 32, 75, 100, 90), ("GuanYu", 24, 85, 96, 88.5),
                   ("ZhaoYun", 28, 85, 92, 96.5), ("HuangZhong", 29, 65, 85, 100)],
                  dtype = persontype)

In [8]:
ages = peoples[:]['age']
ages

array([32, 24, 28, 29], dtype=int32)

In [9]:
print(np.mean(ages))

28.25


In [14]:
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
x1,x2

(array([1, 3, 5, 7, 9]), array([1., 3., 5., 7., 9.]))

In [15]:
print(np.power(x1,x2))

[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]


In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.amin(a), np.amax(a), np.amin(a,0), np.amin(a,1) #0 axis is vertical, 1 axis is horizontal

(1, 9, array([1, 2, 3]), array([1, 4, 7]))

In [23]:
#Difference between biggest value and smallest value
print(np.ptp(a,0))

[6 6 6]


In [28]:
#percentile
np.percentile(a,50)

5.0

In [30]:
#Median & Mean
np.mean(a), np.median(a)

(5.0, 5.0)

In [32]:
#weight average
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
np.average(a,weights = wts)

3.0

In [33]:
#variance and standard deviation
np.std(a),np.var(a)

(1.118033988749895, 1.25)

In [65]:
#sort array
a = np.array([[4, 3, 2], [2, 4, 1]])
a[0]

array([4, 3, 2])

In [102]:
#EXERCISE
datatype = np.dtype({'names':['Name', 'Chinese', 'English', 'Math'],
                    'formats':['S32', 'i', 'i', 'i']})
persons = np.array([('ZhangFei', 66, 65, 30), ('GuanYu', 95, 85, 98), ('ZhaoYun', 93, 92, 96), ('HuangZong', 90, 88, 77), ('Dianwei', 80, 90, 90)],
                  dtype = datatype)
#Chinese
print("Chinese:", "Average = ", np.average(persons[:]['Chinese']), ", Min = ", np.amin(persons[:]['Chinese']),
     ", Max = ", np.amax(persons[:]['Chinese']), ", Var = ", np.var(persons[:]['Chinese']), ", Std = ", np.std(persons[:]['Chinese']))
persons
def Sumscore(n):
    name = persons[n][0]
    Score = persons[n][1] + persons[n][2] + persons[n][3]
    return name, Score
datatype = np.dtype({'names':['Name', 'Total'],
                    'formats':['S32', 'i']})
persons_total = np.array([Sumscore(0), Sumscore(1), Sumscore(2), Sumscore(3), Sumscore(4)],
                  dtype = datatype)
np.sort(persons_total,order='Total')

Chinese: Average =  84.8 , Min =  66 , Max =  95 , Var =  114.96000000000001 , Std =  10.721940122944169


array([(b'ZhangFei', 161), (b'HuangZong', 255), (b'Dianwei', 260),
       (b'GuanYu', 278), (b'ZhaoYun', 281)],
      dtype=[('Name', 'S32'), ('Total', '<i4')])